import type {
  Profile,
  Startup,
  Investor,
  Match,
  IntroRequest,
  Sector,
  FundingStage,
} from "@/types";

// Mock Profiles
export const mockProfiles: Profile[] = [
  {
    id: "profile-1",
    email: "alex@coastlineai.com",
    role: "startup",
    name: "Alex Rivera",
    avatarUrl: undefined,
    createdAt: "2024-01-15T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-2",
    email: "sarah@wineroute.com",
    role: "startup",
    name: "Sarah Chen",
    avatarUrl: undefined,
    createdAt: "2024-01-20T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-3",
    email: "marcus@solarsb.com",
    role: "startup",
    name: "Marcus Johnson",
    avatarUrl: undefined,
    createdAt: "2024-02-01T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-4",
    email: "emily@channelhealth.io",
    role: "startup",
    name: "Emily Park",
    avatarUrl: undefined,
    createdAt: "2024-02-10T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-5",
    email: "david@tidepool.tech",
    role: "startup",
    name: "David Kim",
    avatarUrl: undefined,
    createdAt: "2024-02-15T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-6",
    email: "lisa@kelplabs.com",
    role: "startup",
    name: "Lisa Martinez",
    avatarUrl: undefined,
    createdAt: "2024-02-20T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-7",
    email: "james@harborpay.com",
    role: "startup",
    name: "James Wilson",
    avatarUrl: undefined,
    createdAt: "2024-03-01T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-8",
    email: "nina@coastalrobotics.com",
    role: "startup",
    name: "Nina Patel",
    avatarUrl: undefined,
    createdAt: "2024-03-05T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-9",
    email: "robert@studywave.io",
    role: "startup",
    name: "Robert Lee",
    avatarUrl: undefined,
    createdAt: "2024-03-10T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-10",
    email: "maria@freshharvest.co",
    role: "startup",
    name: "Maria Garcia",
    avatarUrl: undefined,
    createdAt: "2024-03-15T10:00:00Z",
    onboardingComplete: true,
  },
  // Investor profiles
  {
    id: "profile-inv-1",
    email: "jennifer@sbventures.com",
    role: "investor",
    name: "Jennifer Thompson",
    avatarUrl: undefined,
    createdAt: "2024-01-01T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-inv-2",
    email: "michael@coastcapital.com",
    role: "investor",
    name: "Michael Chen",
    avatarUrl: undefined,
    createdAt: "2024-01-05T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-inv-3",
    email: "patricia@pacificangels.com",
    role: "investor",
    name: "Patricia Rodriguez",
    avatarUrl: undefined,
    createdAt: "2024-01-10T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-inv-4",
    email: "steven@channelislands.vc",
    role: "investor",
    name: "Steven Park",
    avatarUrl: undefined,
    createdAt: "2024-01-12T10:00:00Z",
    onboardingComplete: true,
  },
  {
    id: "profile-inv-5",
    email: "amanda@trinityfamily.com",
    role: "investor",
    name: "Amanda Wright",
    avatarUrl: undefined,
    createdAt: "2024-01-15T10:00:00Z",
    onboardingComplete: true,
  },
];

// Mock Startups - the Bay Area themed
export const mockStartups: Startup[] = [
  {
    id: "startup-1",
    profileId: "profile-1",
    companyName: "CoastlineAI",
    tagline: "AI-powered ocean conservation analytics",
    description:
      "We use machine learning to monitor and protect coastal ecosystems, providing real-time insights to marine biologists and environmental agencies.",
    website: "https://coastlineai.com",
    logoUrl: undefined,
    foundedYear: 2023,
    teamSize: 8,
    location: "San Francisco, CA",
    sector: "ai-ml" as Sector,
    stage: "seed" as FundingStage,
    fundingTarget: 2000000,
    fundingRaised: 500000,
    pitchDeckUrl: undefined,
    highlights: [
      "Partnership with Stanford Marine Science Institute",
      "Processing 1M+ data points daily",
      "3 pilot programs with coastal cities",
    ],
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "startup-2",
    profileId: "profile-2",
    companyName: "WineRoute",
    tagline: "Wine country experiences, reimagined",
    description:
      "A marketplace connecting wine enthusiasts with exclusive vineyard experiences in the Bay Area and beyond.",
    website: "https://wineroute.com",
    logoUrl: undefined,
    foundedYear: 2022,
    teamSize: 12,
    location: "San Francisco, CA",
    sector: "marketplace" as Sector,
    stage: "series-a" as FundingStage,
    fundingTarget: 5000000,
    fundingRaised: 1500000,
    pitchDeckUrl: undefined,
    highlights: [
      "50+ partner vineyards",
      "25K monthly active users",
      "Featured in Wine Spectator",
    ],
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-03-05T10:00:00Z",
  },
  {
    id: "startup-3",
    profileId: "profile-3",
    companyName: "SunShare",
    tagline: "Community solar for California renters",
    description:
      "Making solar energy accessible to renters and apartment dwellers through community solar subscriptions.",
    website: "https://solarsb.com",
    logoUrl: undefined,
    foundedYear: 2023,
    teamSize: 6,
    location: "San Francisco, CA",
    sector: "cleantech" as Sector,
    stage: "pre-seed" as FundingStage,
    fundingTarget: 750000,
    fundingRaised: 150000,
    pitchDeckUrl: undefined,
    highlights: [
      "First community solar program in the region",
      "500+ waitlist signups",
      "Partnership with local utility",
    ],
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "startup-4",
    profileId: "profile-4",
    companyName: "ChannelHealth",
    tagline: "Telehealth for coastal communities",
    description:
      "Connecting rural and coastal communities with specialized healthcare providers through our telehealth platform.",
    website: "https://channelhealth.io",
    logoUrl: undefined,
    foundedYear: 2022,
    teamSize: 15,
    location: "San Francisco, CA",
    sector: "healthtech" as Sector,
    stage: "series-a" as FundingStage,
    fundingTarget: 8000000,
    fundingRaised: 3000000,
    pitchDeckUrl: undefined,
    highlights: [
      "10K+ patients served",
      "HIPAA compliant platform",
      "Contracts with 5 rural health networks",
    ],
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: "2024-03-12T10:00:00Z",
  },
  {
    id: "startup-5",
    profileId: "profile-5",
    companyName: "TidePool",
    tagline: "API infrastructure for blue economy data",
    description:
      "Building the data infrastructure that powers the blue economy - from fishing to shipping to marine research.",
    website: "https://tidepool.tech",
    logoUrl: undefined,
    foundedYear: 2023,
    teamSize: 5,
    location: "San Francisco, CA",
    sector: "saas" as Sector,
    stage: "seed" as FundingStage,
    fundingTarget: 3000000,
    fundingRaised: 800000,
    pitchDeckUrl: undefined,
    highlights: [
      "50+ API customers",
      "Processing 10TB of ocean data monthly",
      "NOAA partnership",
    ],
    createdAt: "2024-02-15T10:00:00Z",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "startup-6",
    profileId: "profile-6",
    companyName: "KelpLabs",
    tagline: "Sustainable materials from kelp",
    description:
      "Developing biodegradable packaging and materials from sustainably farmed kelp off the California coast.",
    website: "https://kelplabs.com",
    logoUrl: undefined,
    foundedYear: 2022,
    teamSize: 10,
    location: "San Francisco, CA",
    sector: "biotech" as Sector,
    stage: "seed" as FundingStage,
    fundingTarget: 4000000,
    fundingRaised: 1200000,
    pitchDeckUrl: undefined,
    highlights: [
      "Patent-pending extraction process",
      "Pilot with major CPG company",
      "Carbon negative production",
    ],
    createdAt: "2024-02-20T10:00:00Z",
    updatedAt: "2024-03-18T10:00:00Z",
  },
  {
    id: "startup-7",
    profileId: "profile-7",
    companyName: "HarborPay",
    tagline: "Payment infrastructure for marinas",
    description:
      "Modern payment and management software for marinas, yacht clubs, and boat service providers.",
    website: "https://harborpay.com",
    logoUrl: undefined,
    foundedYear: 2023,
    teamSize: 7,
    location: "San Francisco, CA",
    sector: "fintech" as Sector,
    stage: "seed" as FundingStage,
    fundingTarget: 2500000,
    fundingRaised: 600000,
    pitchDeckUrl: undefined,
    highlights: [
      "20 marina customers",
      "$5M in processed transactions",
      "Integrated with leading marina management systems",
    ],
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-03-20T10:00:00Z",
  },
  {
    id: "startup-8",
    profileId: "profile-8",
    companyName: "CoastalRobotics",
    tagline: "Autonomous drones for coastal inspection",
    description:
      "Autonomous drone systems for inspecting coastal infrastructure, from oil platforms to wind farms.",
    website: "https://coastalrobotics.com",
    logoUrl: undefined,
    foundedYear: 2022,
    teamSize: 14,
    location: "San Francisco, CA",
    sector: "hardware" as Sector,
    stage: "series-a" as FundingStage,
    fundingTarget: 10000000,
    fundingRaised: 4000000,
    pitchDeckUrl: undefined,
    highlights: [
      "FAA Part 107 compliant",
      "Contract with major energy company",
      "50+ successful inspections",
    ],
    createdAt: "2024-03-05T10:00:00Z",
    updatedAt: "2024-03-22T10:00:00Z",
  },
  {
    id: "startup-9",
    profileId: "profile-9",
    companyName: "StudyWave",
    tagline: "Surfing meets studying - gamified learning",
    description:
      "A gamified learning platform that makes education as addictive as social media, with a California surf culture twist.",
    website: "https://studywave.io",
    logoUrl: undefined,
    foundedYear: 2023,
    teamSize: 9,
    location: "San Francisco, CA",
    sector: "edtech" as Sector,
    stage: "pre-seed" as FundingStage,
    fundingTarget: 1000000,
    fundingRaised: 250000,
    pitchDeckUrl: undefined,
    highlights: [
      "100K student signups",
      "Partnership with 3 school districts",
      "40% daily active user rate",
    ],
    createdAt: "2024-03-10T10:00:00Z",
    updatedAt: "2024-03-24T10:00:00Z",
  },
  {
    id: "startup-10",
    profileId: "profile-10",
    companyName: "FreshHarvest",
    tagline: "Farm-to-table logistics for restaurants",
    description:
      "Connecting the Bay Area farms directly with restaurants through smart logistics and real-time inventory.",
    website: "https://freshharvest.co",
    logoUrl: undefined,
    foundedYear: 2022,
    teamSize: 11,
    location: "San Francisco, CA",
    sector: "foodtech" as Sector,
    stage: "seed" as FundingStage,
    fundingTarget: 3500000,
    fundingRaised: 900000,
    pitchDeckUrl: undefined,
    highlights: [
      "75 restaurant partners",
      "30+ local farms onboarded",
      "Reduced food waste by 40%",
    ],
    createdAt: "2024-03-15T10:00:00Z",
    updatedAt: "2024-03-26T10:00:00Z",
  },
];

// Mock Investors
export const mockInvestors: Investor[] = [
  {
    id: "investor-1",
    profileId: "profile-inv-1",
    firmName: "the Bay Area Ventures",
    title: "Managing Partner",
    bio: "Early-stage investor focused on West Coast startups. Former founder with 2 exits. Passionate about backing founders who are building the future of California.",
    website: "https://sbventures.com",
    logoUrl: undefined,
    location: "San Francisco, CA",
    investorType: "vc",
    checkSizeMin: 250000,
    checkSizeMax: 2000000,
    preferredStages: ["pre-seed", "seed"] as FundingStage[],
    preferredSectors: ["ai-ml", "cleantech", "saas", "healthtech"] as Sector[],
    portfolioCount: 24,
    thesis:
      "We invest in technical founders building category-defining companies on the West Coast. We believe great companies can be built anywhere, and the Bay Area is becoming the next great tech hub.",
    createdAt: "2024-01-01T10:00:00Z",
    updatedAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "investor-2",
    profileId: "profile-inv-2",
    firmName: "Coast Capital Partners",
    title: "General Partner",
    bio: "Series A focused fund investing in B2B software and marketplace companies. 15 years of venture experience, previously at top-tier Silicon Valley firms.",
    website: "https://coastcapital.com",
    logoUrl: undefined,
    location: "San Francisco, CA",
    investorType: "vc",
    checkSizeMin: 1000000,
    checkSizeMax: 5000000,
    preferredStages: ["seed", "series-a"] as FundingStage[],
    preferredSectors: ["saas", "marketplace", "fintech"] as Sector[],
    portfolioCount: 18,
    thesis:
      "We partner with exceptional founders building software that transforms how businesses operate. We look for strong unit economics, clear path to profitability, and defensible moats.",
    createdAt: "2024-01-05T10:00:00Z",
    updatedAt: "2024-03-05T10:00:00Z",
  },
  {
    id: "investor-3",
    profileId: "profile-inv-3",
    firmName: "Pacific Angel Network",
    title: "Lead Angel",
    bio: "Angel investor and startup advisor. Exited 3 companies as founder. Now helping the next generation of entrepreneurs through capital and mentorship.",
    website: "https://pacificangels.com",
    logoUrl: undefined,
    location: "San Francisco, CA",
    investorType: "angel",
    checkSizeMin: 25000,
    checkSizeMax: 150000,
    preferredStages: ["pre-seed", "seed"] as FundingStage[],
    preferredSectors: [
      "consumer",
      "edtech",
      "foodtech",
      "marketplace",
    ] as Sector[],
    portfolioCount: 35,
    thesis:
      "I invest in founders, not just ideas. Looking for passionate entrepreneurs solving real problems they've personally experienced. Consumer and education sectors preferred.",
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "investor-4",
    profileId: "profile-inv-4",
    firmName: "Channel Islands Ventures",
    title: "Partner",
    bio: "Deep tech investor specializing in hardware, robotics, and biotech. PhD in Mechanical Engineering from Caltech. Former VP of Engineering at a Fortune 500 company.",
    website: "https://channelislands.vc",
    logoUrl: undefined,
    location: "San Francisco, CA",
    investorType: "vc",
    checkSizeMin: 500000,
    checkSizeMax: 3000000,
    preferredStages: ["seed", "series-a", "series-b"] as FundingStage[],
    preferredSectors: ["hardware", "biotech", "cleantech", "ai-ml"] as Sector[],
    portfolioCount: 12,
    thesis:
      "We invest in breakthrough technologies that can reshape industries. We're patient capital willing to support long R&D cycles. Strong preference for companies with defensible IP.",
    createdAt: "2024-01-12T10:00:00Z",
    updatedAt: "2024-03-12T10:00:00Z",
  },
  {
    id: "investor-5",
    profileId: "profile-inv-5",
    firmName: "Trinity Family Office",
    title: "Investment Director",
    bio: "Multi-family office making direct investments in growth-stage companies. We bring more than capital - our network includes industry executives, operators, and policy makers.",
    website: "https://trinityfamily.com",
    logoUrl: undefined,
    location: "Palo Alto, CA",
    investorType: "family-office",
    checkSizeMin: 2000000,
    checkSizeMax: 10000000,
    preferredStages: ["series-a", "series-b", "series-c"] as FundingStage[],
    preferredSectors: [
      "healthtech",
      "fintech",
      "cleantech",
      "consumer",
    ] as Sector[],
    portfolioCount: 8,
    thesis:
      "We invest in companies making a positive impact on society while generating strong returns. ESG considerations are important to our investment decisions. We value long-term relationships with founders.",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-03-15T10:00:00Z",
  },
];

// Mock Matches with pre-calculated scores
export const mockMatches: Match[] = [
  {
    id: "match-1",
    startupId: "startup-1",
    investorId: "investor-1",
    score: 92,
    scoreBreakdown: {
      stageAlignment: 25,
      sectorMatch: 30,
      checkSizeFit: 22,
      locationBonus: 15,
    },
    status: "pending",
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "match-2",
    startupId: "startup-1",
    investorId: "investor-4",
    score: 85,
    scoreBreakdown: {
      stageAlignment: 20,
      sectorMatch: 30,
      checkSizeFit: 20,
      locationBonus: 15,
    },
    status: "viewed",
    createdAt: "2024-03-02T10:00:00Z",
    viewedAt: "2024-03-03T10:00:00Z",
  },
  {
    id: "match-3",
    startupId: "startup-2",
    investorId: "investor-2",
    score: 88,
    scoreBreakdown: {
      stageAlignment: 25,
      sectorMatch: 28,
      checkSizeFit: 20,
      locationBonus: 15,
    },
    status: "intro-requested",
    createdAt: "2024-03-03T10:00:00Z",
  },
  {
    id: "match-4",
    startupId: "startup-3",
    investorId: "investor-1",
    score: 78,
    scoreBreakdown: {
      stageAlignment: 25,
      sectorMatch: 25,
      checkSizeFit: 13,
      locationBonus: 15,
    },
    status: "pending",
    createdAt: "2024-03-04T10:00:00Z",
  },
  {
    id: "match-5",
    startupId: "startup-4",
    investorId: "investor-5",
    score: 91,
    scoreBreakdown: {
      stageAlignment: 25,
      sectorMatch: 30,
      checkSizeFit: 21,
      locationBonus: 15,
    },
    status: "connected",
    createdAt: "2024-03-05T10:00:00Z",
  },
  {
    id: "match-6",
    startupId: "startup-5",
    investorId: "investor-2",
    score: 82,
    scoreBreakdown: {
      stageAlignment: 22,
      sectorMatch: 28,
      checkSizeFit: 17,
      locationBonus: 15,
    },
    status: "pending",
    createdAt: "2024-03-06T10:00:00Z",
  },
  {
    id: "match-7",
    startupId: "startup-6",
    investorId: "investor-4",
    score: 94,
    scoreBreakdown: {
      stageAlignment: 25,
      sectorMatch: 30,
      checkSizeFit: 24,
      locationBonus: 15,
    },
    status: "intro-requested",
    createdAt: "2024-03-07T10:00:00Z",
  },
  {
    id: "match-8",
    startupId: "startup-7",
    investorId: "investor-2",
    score: 86,
    scoreBreakdown: {
      stageAlignment: 22,
      sectorMatch: 30,
      checkSizeFit: 19,
      locationBonus: 15,
    },
    status: "pending",
    createdAt: "2024-03-08T10:00:00Z",
  },
  {
    id: "match-9",
    startupId: "startup-8",
    investorId: "investor-4",
    score: 89,
    scoreBreakdown: {
      stageAlignment: 25,
      sectorMatch: 30,
      checkSizeFit: 19,
      locationBonus: 15,
    },
    status: "viewed",
    createdAt: "2024-03-09T10:00:00Z",
    viewedAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "match-10",
    startupId: "startup-9",
    investorId: "investor-3",
    score: 76,
    scoreBreakdown: {
      stageAlignment: 25,
      sectorMatch: 25,
      checkSizeFit: 11,
      locationBonus: 15,
    },
    status: "pending",
    createdAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "match-11",
    startupId: "startup-10",
    investorId: "investor-3",
    score: 84,
    scoreBreakdown: {
      stageAlignment: 22,
      sectorMatch: 28,
      checkSizeFit: 19,
      locationBonus: 15,
    },
    status: "intro-requested",
    createdAt: "2024-03-11T10:00:00Z",
  },
  {
    id: "match-12",
    startupId: "startup-3",
    investorId: "investor-4",
    score: 71,
    scoreBreakdown: {
      stageAlignment: 18,
      sectorMatch: 28,
      checkSizeFit: 10,
      locationBonus: 15,
    },
    status: "declined",
    createdAt: "2024-03-12T10:00:00Z",
  },
];

// Mock Intro Requests
export const mockIntroRequests: IntroRequest[] = [
  {
    id: "intro-1",
    matchId: "match-3",
    senderId: "profile-2",
    receiverId: "profile-inv-2",
    message:
      "Hi Michael, I'd love to connect about WineRoute. We're seeing great traction in the wine tourism space and I think our marketplace model aligns well with your investment thesis.",
    status: "pending",
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "intro-2",
    matchId: "match-5",
    senderId: "profile-4",
    receiverId: "profile-inv-5",
    message:
      "Amanda, ChannelHealth is transforming rural healthcare access. Given Trinity's focus on impact investing, I believe we could be a great fit for your portfolio.",
    status: "accepted",
    createdAt: "2024-03-10T10:00:00Z",
    respondedAt: "2024-03-12T10:00:00Z",
  },
  {
    id: "intro-3",
    matchId: "match-7",
    senderId: "profile-6",
    receiverId: "profile-inv-4",
    message:
      "Steven, KelpLabs is pioneering sustainable biomaterials. Our patent-pending technology could be a great addition to your deep tech portfolio.",
    status: "pending",
    createdAt: "2024-03-18T10:00:00Z",
  },
  {
    id: "intro-4",
    matchId: "match-11",
    senderId: "profile-10",
    receiverId: "profile-inv-3",
    message:
      "Patricia, FreshHarvest is solving real problems in farm-to-table logistics. Would love to share how we're reducing food waste while helping local restaurants.",
    status: "pending",
    createdAt: "2024-03-20T10:00:00Z",
  },
];

// Helper functions to get data
export function getStartupById(id: string): Startup | undefined {
  return mockStartups.find((s) => s.id === id);
}

export function getInvestorById(id: string): Investor | undefined {
  return mockInvestors.find((i) => i.id === id);
}

export function getProfileById(id: string): Profile | undefined {
  return mockProfiles.find((p) => p.id === id);
}

export function getMatchesForStartup(startupId: string): Match[] {
  return mockMatches.filter((m) => m.startupId === startupId);
}

export function getMatchesForInvestor(investorId: string): Match[] {
  return mockMatches.filter((m) => m.investorId === investorId);
}

export function getIntroRequestsForUser(userId: string): IntroRequest[] {
  return mockIntroRequests.filter(
    (ir) => ir.senderId === userId || ir.receiverId === userId
  );
}

// Demo user for development
export const demoStartupUser = {
  profile: mockProfiles[0],
  startup: mockStartups[0],
};

export const demoInvestorUser = {
  profile: mockProfiles[10],
  investor: mockInvestors[0],
};
